-- Only remove bindings generated by this migration. Later user-driven
-- reinstalls have a distinct opaque installation id and are preserved.
DELETE FROM app_installations ai
USING humans h
WHERE ai.owner_kind = 'human'
  AND ai.owner_id = h.human_id
  AND ai.app_id = 'direct-chat'
  AND ai.installation_id =
      substr(h.human_id, 1, 14) || '7' ||
      substr(md5('sumi:direct-chat-backfill:v1:' || h.human_id), 1, 3) ||
      '-8' ||
      substr(md5('sumi:direct-chat-backfill:v1:' || h.human_id), 4, 3) ||
      '-' ||
      substr(md5('sumi:direct-chat-backfill:v1:' || h.human_id), 7, 12);
