/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DirectRouteImport } from './routes/direct'
import { Route as IndexRouteImport } from './routes/index'

const DirectRoute = DirectRouteImport.update({
  id: '/direct',
  path: '/direct',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/direct': typeof DirectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/direct': typeof DirectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/direct': typeof DirectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/direct'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/direct'
  id: '__root__' | '/' | '/direct'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DirectRoute: typeof DirectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/direct': {
      id: '/direct'
      path: '/direct'
      fullPath: '/direct'
      preLoaderRoute: typeof DirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DirectRoute: DirectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
