/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DirectRouteImport } from './routes/direct'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TThreadIdRouteImport } from './routes/t.$threadId'
import { Route as GroupDmIdRouteImport } from './routes/group.$dmId'
import { Route as DmDmIdRouteImport } from './routes/dm.$dmId'
import { Route as CChannelIdRouteImport } from './routes/c.$channelId'

const DirectRoute = DirectRouteImport.update({
  id: '/direct',
  path: '/direct',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TThreadIdRoute = TThreadIdRouteImport.update({
  id: '/t/$threadId',
  path: '/t/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupDmIdRoute = GroupDmIdRouteImport.update({
  id: '/group/$dmId',
  path: '/group/$dmId',
  getParentRoute: () => rootRouteImport,
} as any)
const DmDmIdRoute = DmDmIdRouteImport.update({
  id: '/dm/$dmId',
  path: '/dm/$dmId',
  getParentRoute: () => rootRouteImport,
} as any)
const CChannelIdRoute = CChannelIdRouteImport.update({
  id: '/c/$channelId',
  path: '/c/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/direct': typeof DirectRoute
  '/c/$channelId': typeof CChannelIdRoute
  '/dm/$dmId': typeof DmDmIdRoute
  '/group/$dmId': typeof GroupDmIdRoute
  '/t/$threadId': typeof TThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/direct': typeof DirectRoute
  '/c/$channelId': typeof CChannelIdRoute
  '/dm/$dmId': typeof DmDmIdRoute
  '/group/$dmId': typeof GroupDmIdRoute
  '/t/$threadId': typeof TThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/direct': typeof DirectRoute
  '/c/$channelId': typeof CChannelIdRoute
  '/dm/$dmId': typeof DmDmIdRoute
  '/group/$dmId': typeof GroupDmIdRoute
  '/t/$threadId': typeof TThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/direct'
    | '/c/$channelId'
    | '/dm/$dmId'
    | '/group/$dmId'
    | '/t/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/direct'
    | '/c/$channelId'
    | '/dm/$dmId'
    | '/group/$dmId'
    | '/t/$threadId'
  id:
    | '__root__'
    | '/'
    | '/direct'
    | '/c/$channelId'
    | '/dm/$dmId'
    | '/group/$dmId'
    | '/t/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DirectRoute: typeof DirectRoute
  CChannelIdRoute: typeof CChannelIdRoute
  DmDmIdRoute: typeof DmDmIdRoute
  GroupDmIdRoute: typeof GroupDmIdRoute
  TThreadIdRoute: typeof TThreadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/direct': {
      id: '/direct'
      path: '/direct'
      fullPath: '/direct'
      preLoaderRoute: typeof DirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$threadId': {
      id: '/t/$threadId'
      path: '/t/$threadId'
      fullPath: '/t/$threadId'
      preLoaderRoute: typeof TThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$dmId': {
      id: '/group/$dmId'
      path: '/group/$dmId'
      fullPath: '/group/$dmId'
      preLoaderRoute: typeof GroupDmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dm/$dmId': {
      id: '/dm/$dmId'
      path: '/dm/$dmId'
      fullPath: '/dm/$dmId'
      preLoaderRoute: typeof DmDmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$channelId': {
      id: '/c/$channelId'
      path: '/c/$channelId'
      fullPath: '/c/$channelId'
      preLoaderRoute: typeof CChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DirectRoute: DirectRoute,
  CChannelIdRoute: CChannelIdRoute,
  DmDmIdRoute: DmDmIdRoute,
  GroupDmIdRoute: GroupDmIdRoute,
  TThreadIdRoute: TThreadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
