package workspace

import (
	"context"
	"crypto/sha256"
	"encoding/base64"
	"errors"
	"io"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/sumi-studio/sumi/apps/api/internal/koseki"
	"github.com/sumi-studio/sumi/apps/api/internal/participant"
)

type EnrollmentRecipientProof struct {
	FirebaseUID   string
	Email         string
	EmailVerified bool
}
type EnrollmentInviteIssuer interface {
	IssueEnrollmentInviteInTx(context.Context, pgx.Tx, string, string, time.Duration) (koseki.EnrollmentInvite, string, error)
}
type EnrollmentBundleGrant struct {
	ID        string    `json:"id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (s *Store) CreateEnrollmentBundle(ctx context.Context, workspaceID string, actor participant.Ref, email string, issuer EnrollmentInviteIssuer) (Invite, error) {
	if actor.Kind != participant.KindHuman || issuer == nil || s.EnrollmentAdmin == nil || !s.EnrollmentAdmin(actor.ID) {
		return Invite{}, ErrForbidden
	}
	raw := make([]byte, inviteEntropyBytes)
	if _, err := io.ReadFull(s.random, raw); err != nil {
		return Invite{}, err
	}
	code := base64.RawURLEncoding.EncodeToString(raw)
	hash := sha256.Sum256([]byte(code))
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return Invite{}, err
	}
	defer tx.Rollback(ctx)
	member, err := s.lockAndRequirePermission(ctx, tx, workspaceID, actor, PermissionManageMembers)
	if err != nil {
		return Invite{}, err
	}
	// Both grants share one expiration, generated by the database within the
	// transaction. A failed second grant rolls back the first.
	enrollment, token, err := issuer.IssueEnrollmentInviteInTx(ctx, tx, actor.ID, email, s.inviteTTL)
	if err != nil {
		if errors.Is(err, koseki.ErrEnrollmentInvite) {
			return Invite{}, ErrInvalidEnrollmentInvitation
		}
		return Invite{}, err
	}
	v := Invite{InviteID: newUUIDv7(), WorkspaceID: workspaceID, Code: code, CreatedAt: enrollment.CreatedAt, ExpiresAt: enrollment.ExpiresAt, Enrollment: &EnrollmentBundleGrant{ID: enrollment.ID, Token: token, ExpiresAt: enrollment.ExpiresAt}}
	_, err = tx.Exec(ctx, `INSERT INTO workspace_invites(invite_id,workspace_id,created_by_workspace_member_id,code_hash,created_at,expires_at) VALUES($1,$2,$3,$4,$5,$6)`, v.InviteID, workspaceID, member, hash[:], v.CreatedAt, v.ExpiresAt)
	if err != nil {
		return Invite{}, err
	}
	if _, err = tx.Exec(ctx, `UPDATE enrollment_invites SET workspace_invite_id=$2 WHERE invite_id=$1`, enrollment.ID, v.InviteID); err != nil {
		return Invite{}, err
	}
	if err = tx.Commit(ctx); err != nil {
		return Invite{}, err
	}
	return v, nil
}

func (s *Store) LockEnrollmentWorkspaceInvite(ctx context.Context, tx pgx.Tx, inviteID string) error {
	var workspaceID string
	if err := tx.QueryRow(ctx, `SELECT workspace_id FROM workspace_invites WHERE invite_id=$1`, inviteID).Scan(&workspaceID); err != nil {
		return err
	}
	if err := lockWorkspace(ctx, tx, workspaceID); err != nil {
		return err
	}
	_, err := tx.Exec(ctx, `SELECT invite_id FROM workspace_invites WHERE invite_id=$1 FOR UPDATE`, inviteID)
	return err
}
func (s *Store) ValidateEnrollmentWorkspaceInvite(ctx context.Context, tx pgx.Tx, inviteID string) error {
	var workspaceID, issuer string
	var valid bool
	err := tx.QueryRow(ctx, `SELECT workspace_id,created_by_workspace_member_id,(revoked_at IS NULL AND redeemed_at IS NULL AND reserved_human_id IS NULL AND expires_at>clock_timestamp()) FROM workspace_invites WHERE invite_id=$1`, inviteID).Scan(&workspaceID, &issuer, &valid)
	if err != nil {
		return err
	}
	if !valid {
		return ErrInviteUnavailable
	}
	return requireInviteIssuerAuthority(ctx, tx, workspaceID, issuer)
}

// Called only after Workspace and Workspace invite locks. No other identity
// may take the join step after enrollment has reserved it for a Human.
func requireBundleRecipient(ctx context.Context, tx pgx.Tx, codeHash []byte, actor participant.Ref, proof EnrollmentRecipientProof) error {
	var inviteID, email, reserved, consumed string
	var revoked *time.Time
	var live bool
	err := tx.QueryRow(ctx, `SELECT ei.invite_id,COALESCE(ei.email,''),COALESCE(wi.reserved_human_id::text,''),COALESCE(ei.consumed_by::text,''),ei.revoked_at,ei.expires_at>clock_timestamp()
 FROM workspace_invites wi JOIN enrollment_invites ei ON ei.workspace_invite_id=wi.invite_id WHERE wi.code_hash=$1 FOR UPDATE OF ei`, codeHash).Scan(&inviteID, &email, &reserved, &consumed, &revoked, &live)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil
	}
	if err != nil {
		return err
	}
	if actor.Kind != participant.KindHuman || !live {
		return ErrInviteUnavailable
	}
	if reserved != "" {
		if reserved != actor.ID || consumed != actor.ID {
			return ErrInviteUnavailable
		}
		return nil
	}
	if revoked != nil || consumed != "" || !live {
		return ErrInviteUnavailable
	}
	if email != "" {
		if !proof.EmailVerified || proof.Email != email || proof.FirebaseUID == "" {
			return ErrInviteEmailVerification
		}
		var bound bool
		if err = tx.QueryRow(ctx, `SELECT EXISTS(SELECT 1 FROM credentials WHERE provider='firebase' AND external_subject=$1 AND human_id=$2 AND active)`, proof.FirebaseUID, actor.ID).Scan(&bound); err != nil {
			return err
		}
		if !bound {
			return ErrInviteEmailVerification
		}
	}
	return nil
}
func closeBundleEnrollment(ctx context.Context, tx pgx.Tx, codeHash []byte, humanID string) error {
	_, err := tx.Exec(ctx, `UPDATE enrollment_invites SET revoked_at=COALESCE(revoked_at,clock_timestamp()) WHERE workspace_invite_id=(SELECT invite_id FROM workspace_invites WHERE code_hash=$1) AND consumed_at IS NULL`, codeHash)
	if err != nil {
		return err
	}
	_, err = tx.Exec(ctx, `UPDATE workspace_invites SET reserved_human_id=$2 WHERE code_hash=$1 AND EXISTS(SELECT 1 FROM enrollment_invites WHERE workspace_invite_id=workspace_invites.invite_id)`, codeHash, humanID)
	return err
}

var ErrInviteEmailVerification = errors.New("verified invitation email required")

func finishShareInvite(ctx context.Context, tx pgx.Tx, hash []byte, actor participant.Ref, membership Membership, now time.Time) error {
	if _, err := tx.Exec(ctx, `UPDATE workspace_invites SET redeemed_by_kind=$2,redeemed_by_id=$3,redeemed_workspace_member_id=$4,redeemed_at=$5 WHERE code_hash=$1`, hash, actor.Kind, actor.ID, membership.WorkspaceMemberID, now); err != nil {
		return err
	}
	return closeBundleEnrollment(ctx, tx, hash, actor.ID)
}

var ErrInvalidEnrollmentInvitation = errors.New("invalid enrollment invitation")
